advance on refactor

diff --git a/scripts/SebalInfra/deploy_crawler b/scripts/SebalInfra/deploy_crawler
--- a/scripts/SebalInfra/deploy_crawler
+++ b/scripts/SebalInfra/deploy_crawler
@@ -1,20 +1,36 @@
 #!/bin/bash
 #
-# Deploy of the crawler component
+# Deploy the crawler component
 
-#FIXME: check args
+#FIXME add classpath and class names to constants
+
+if [[ $# -ne 2 ]]; then
+  echo "Usage:" $0 "path/to/private_key storage_size"
+  exit 1
+fi
+
 PRIVATE_KEY_FILE=$1
 STORAGE_SIZE=$2
 
-#FIXME: indent
-LOG4J=target/classe/log4j.properties
-if [ -f $LOG4J ]; then
-CONF_LOG=-Dlog4j.configuration=file:$LOG4J
-else
-CONF_LOG=
+if [[ ! -f "${PRIVATE_KEY_FILE}" ]]; then
+  echo $PRIVATE_KEY_FILE "is not a regular file or does not exist"
+  exit 1
 fi
 
-#FIXME: not sure if we should keep these declarations here or to load from a config file
+if [[ ! "${STORAGE_SIZE}" =~ ^[0-9]+$ ]]; then
+  echo "Invalid storage_size" $STORAGE_SIZE
+  exit 1
+fi
+
+#FIXME should not use target/classe
+LOG4J=target/classe/log4j.properties
+if [[ -f ${LOG4J} ]]; then
+  CONF_LOG=-Dlog4j.configuration=file:$LOG4J
+else
+  CONF_LOG=
+fi
+
+#FIXME not sure if we should keep these declarations here or to load from a config file
 #GLOBAL CONSTANTS
 APP_FILE=sebal-scheduler-project.tar.gz
 APP_FILE_LOCAL_DIR=baseapp
@@ -43,7 +59,7 @@ fi
 
 source $CRAWLER_EXECUTION_INFO
 
-#FIXME: add some doc. i did not understand the purpose of below code
+#FIXME add some doc. i did not understand the purpose of below code
 STORAGE_COMMAND="FORMAT";
 
 if [ "$CRAWLER_STORAGE_FORMATED" = "YES" ]; then
@@ -54,21 +70,42 @@ echo "Storage command: $STORAGE_COMMAND";
 
 ########### CRAWLER INFRASTRUCTURE ##############
 
-#FIXME: extract to a function
+# It wrapps the java call to the Infrastructure main
+# Globals
+#   CONF_LOG
+# Args
+#   java_args
+# Returns
+function infra_call() {
+  local java_args=$1
+  cmd_out="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain compute $CONFIG_FILE $SPEC_FILE 2>&1)"
+  echo $cmd_out
+}
 
-#Starting infrastructure for Crawler.
-#Verify the rigths paths for crawler.conf and crawlerSpec
-CONFIG_FILE=target/classes/sebal.conf 
-SPEC_FILE=target/classes/crawlerSpec
-echo "Requesting Instance for Crawler".
-VM_CRAWLER_INFO="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain compute $CONFIG_FILE $SPEC_FILE 2>&1)";
-echo $VM_CRAWLER_INFO
-if [[ ! $VM_CRAWLER_INFO == *"INSTANCE_ID"* ]]; then
-	echo $VM_CRAWLER_INFO
-	echo "There is no resource available for deploy Crawler App."
-	exit
-fi
-echo "Instance sucessfully requested".
+#FIXME remove vars from inside the function. should be global
+#FIXME improve contains test
+
+# It starts crawler VM
+# Globals
+#   CONFIG_FILE
+#   SPEC_FILE
+# Returns
+#   infrastructure description
+function create_crawler_vm() {
+  #CONFIG_FILE=target/classes/sebal.conf
+  #SPEC_FILE=target/classes/crawlerSpec
+
+  create_arsg="compute $CONFIG_FILE $SPEC_FILE"
+  VM_CRAWLER_INFO=`infra_call ${create_args}`
+
+  if [[ ! $VM_CRAWLER_INFO == *"INSTANCE_ID"* ]]; then
+    echo $VM_CRAWLER_INFO
+    echo "There is no resource available for deploy Crawler App." >&2
+    exit 1
+  fi
+
+  echo $VM_CRAWLER_INFO
+}
 
 #PREPARING VARIABLES FOR SSH/SCP
 #Sample return USER_NAME=fogbow;SSH_HOST=192.168.0.1;SSH_HOST=9000;SSH_HOST=
@@ -85,137 +122,168 @@ echo $INSTANCE_PORT;
 echo $EXTRA_PORT;
 echo $CRAWLER_STORAGE_PORT;
 
-#Request Storage for Crawler
+#FIXME improve function. we need return values
+# It Verifies if storage info exists.
+# Globals
+#   CRAWLER_STORAGE_ID
+#   CONFIG_FILE
+#   SPEC_FILE
+# Args
+#  CRAWLER_STORAGE_ID
+function storage_exists() {
+  if [ -n "$CRAWLER_STORAGE_ID" ]; then
+    check_exits_args="test-storage $CRAWLER_STORAGE_ID $CONFIG_FILE $SPEC_FILE";
+    STORAGE_STATUS=`infra_call $check_exits_args`
+    STORAGE_STATUS=$(echo $STORAGE_STATUS | cut -d";" -f1 | cut -d"=" -f2)
+    echo "Storage status: $STORAGE_STATUS";
+    if [ ! $STORAGE_STATUS = "active" ]; then
+      CRAWLER_STORAGE_ID="";
+    fi
+  fi
+}
 
-#FIXME: extract to a method
-#Verify if storage info exists. If true, the storage for Crawler already exists and dont need to create new one.
-echo "Previous Storage ID: $CRAWLER_STORAGE_ID";
-if [ -n "$CRAWLER_STORAGE_ID" ]; then
+# It creates a volume
+# Globals
+# Args
+# Returns
+function create_volume() {
+  #FIXME check args
+  STORAGE_COMMAND="FORMAT";
+  sed -i "/CRAWLER_STORAGE_FORMATED=/ s/=.*/=NO/" $CRAWLER_EXECUTION_INFO
 
-	echo "Storage found. ID: $CRAWLER_STORAGE_ID"
+  #This tow variables indicates if a new storage is been used. For new storage, the disk must be formated and the database must be created.
+  create_vol_args="storage $STORAGE_SIZE $CONFIG_FILE $SPEC_FILE"
+  STORAGE_INFO=`infra_call $create_vol_args`
+  echo $STORAGE_INFO
 
-  	STORAGE_STATUS="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain test-storage $CRAWLER_STORAGE_ID $CONFIG_FILE $SPEC_FILE 2>&1)";
-  	STORAGE_STATUS=$(echo $STORAGE_STATUS | cut -d";" -f1 | cut -d"=" -f2)
-  	echo "Storage status: $STORAGE_STATUS";
-  	if [ ! $STORAGE_STATUS = "active" ]; then
-  		CRAWLER_STORAGE_ID="";
-  	fi
-fi
+  CRAWLER_STORAGE_ID=$(echo $STORAGE_INFO | cut -d";" -f1 | cut -d"=" -f2)
 
-#FIXME: ident, extract to a method
-if [ -z "$CRAWLER_STORAGE_ID" ]; then
+  echo "New storage created: "$CRAWLER_STORAGE_ID
+}
 
-echo "Creating new Storage with size $STORAGE_SIZE"
+# it attaches the volume to the VM
+# Globals
+# Args
+# Returns
+function attach_volume() {
+#FIXME check vars
+#FIXME add proper return
+  echo "Attaching $CRAWLER_STORAGE_ID to $INSTANCE_ID"
+  attach_arg="attachment $INSTANCE_ID $CRAWLER_STORAGE_ID $CONFIG_FILE $SPEC_FILE"
+  CRAWLER_STORAGE_ATTACHMENT_INFO=`infra_call $attach_args`
 
-STORAGE_COMMAND="FORMAT";
+  if [[ ! $CRAWLER_STORAGE_ATTACHMENT_INFO == *"ATTACHMENT_ID"* ]]; then
+    echo $CRAWLER_STORAGE_ATTACHMENT_INFO
+    echo "Error while attaching $CRAWLER_STORAGE_ID to $INSTANCE_ID."
+    exit
+  fi
 
-sed -i "/CRAWLER_STORAGE_FORMATED=/ s/=.*/=NO/" $CRAWLER_EXECUTION_INFO
+  echo $CRAWLER_STORAGE_ATTACHMENT_INFO;
+  CRAWLER_STORAGE_ATTACHMENT_ID=$(echo $CRAWLER_STORAGE_ATTACHMENT_INFO | cut -d";" -f1 | cut -d"=" -f2)
+  echo "Attach ID: $CRAWLER_STORAGE_ATTACHMENT_ID"
+  #Update Storage INFO FILE with the new attachment id.
+  sed -i "/CRAWLER_STORAGE_ATTACHMENT_ID=/ s/=.*/=$CRAWLER_STORAGE_ATTACHMENT_ID/" $CRAWLER_EXECUTION_INFO
+}
 
-#This tow variables indicates if a new storage is been used. For new storage, the disk must be formated and the database must be created.
-STORAGE_INFO="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain storage $STORAGE_SIZE $CONFIG_FILE $SPEC_FILE 2>&1)";
-echo $STORAGE_INFO
-
-CRAWLER_STORAGE_ID=$(echo $STORAGE_INFO | cut -d";" -f1 | cut -d"=" -f2)
-
-echo "New storage created: "$CRAWLER_STORAGE_ID;
-
-fi
-
-#FIXME: extract to a method
-#Attach the storage to the VM.
-echo "Attaching $CRAWLER_STORAGE_ID to $INSTANCE_ID";
-CRAWLER_STORAGE_ATTACHMENT_INFO="$(java $CONF_LOG -cp target/sebal-scheduler-0.0.1-SNAPSHOT.jar:target/lib/* org.fogbowcloud.infrastructure.InfrastructureMain attachment $INSTANCE_ID $CRAWLER_STORAGE_ID $CONFIG_FILE $SPEC_FILE 2>&1)";
-
-if [[ ! $CRAWLER_STORAGE_ATTACHMENT_INFO == *"ATTACHMENT_ID"* ]]; then
-	echo $CRAWLER_STORAGE_ATTACHMENT_INFO
-	echo "Erro while attaching $CRAWLER_STORAGE_ID to $INSTANCE_ID."
-	exit
-fi
-
-echo $CRAWLER_STORAGE_ATTACHMENT_INFO;
-
-CRAWLER_STORAGE_ATTACHMENT_ID=$(echo $CRAWLER_STORAGE_ATTACHMENT_INFO | cut -d";" -f1 | cut -d"=" -f2)
-
-echo "Attach ID: $CRAWLER_STORAGE_ATTACHMENT_ID";
-
-#Update Storage INFO FILE with the new attachment id.
-sed -i "/CRAWLER_STORAGE_ATTACHMENT_ID=/ s/=.*/=$CRAWLER_STORAGE_ATTACHMENT_ID/" $CRAWLER_EXECUTION_INFO
-
-#FIXME: no need to echo the remove command
-
-#FIXME: extract to a method
+#FIXME extract to a method
 #Coping scripts to mount disk.
 LOCAL_FILE_PATH="sebal_scripts"
 REMOTE_FILE_PATH="$REMOTE_BASE_DIR";
 
-#FIXME: extract to a method
-echo "UPLOAD SCRIPTS..."
-echo "scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH/ $USER_NAME@$INSTANCE_IP:/$REMOTE_FILE_PATH"
-scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH/ $USER_NAME@$INSTANCE_IP:/$REMOTE_FILE_PATH
+# SSH to crawler VM
+# Globals
+#   INSTANCE_PORT
+#   PRIVATE_KEY_FILE
+#   USER_NAME
+#   INSTANCE_IP
+# Args
+#   remote_command
+# Returns
+function ssh_to_crawler() {
+  #FIXME check remote_command?
+  local remote_command=$1
+  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $remote_command
+}
 
-#FIXME: extract to a method
-echo "ALTER PERMISSION FOR SCRIPTS..."
-REMOTE_COMMAND="sudo chmod -R 777 /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH";
-echo "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND"
-ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND
+# Globals
+#   INSTANCE_PORT
+#   PRIVATE_KEY_FILE
+#   USER_NAME
+#   INSTANCE_IP
+# Args
+#   src_path
+#   dst_path
+# Returns
+function scp_to_crawler() {
+  #FIXME how about the -r modified?
+  local src_path=$1
+  local dst_path=$2
+  scp -r -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $src_path $USER_NAME@$INSTANCE_IP:/$dst_path
+}
 
-#FIXME: extract to a method
-#Preparing storage
-echo "PREPARING STORAGE..."
-REMOTE_COMMAND="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/mount_partition.sh $STORAGE_COMMAND";
-echo  "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND"
-ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND
-sed -i "/CRAWLER_STORAGE_FORMATED=/ s/=.*/=YES/" $CRAWLER_EXECUTION_INFO
+# Globals
+#   EXTRA_PORT
+# Args
+# Returns
+#  nfs_port
+function parse_nfs_port() {
+  IFS=',' read -r -a extraPortsArray <<< $EXTRA_PORT
+  arrayLength=${#extraPortsArray[@]};
+  for (( i=0; i<${arrayLength}; i++ ));
+  do
+    actualPort=${extraPortsArray[$i]};
+    if [[ $actualPort == *"nfs"* ]]; then
+      nfs_port=`$actualPort | cut -d":" -f3 | tr -d`
+      echo $nfs_port
+    fi
+  done
+}
 
-#FIXME: extract to a method
-#Installing git
-echo "INSTALLING GIT..."
-REMOTE_COMMAND="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/install_git.sh";
-echo "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND"
-ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND
+function main() {
+  echo "Uploading scripts"
+  scp_to_crawler $LOCAL_FILE_PATH/ $REMOVE_FILE_PATH
 
-#FIXME: extract to a method
-# see if the name of the project will change
-#Coping SEBAL-Scheduler App file to Crawler VM
-echo "UPLOAD CRAWLER PACKAGE..."
-LOCAL_FILE_PATH="$APP_FILE_LOCAL_DIR/$APP_FILE"
-REMOTE_FILE_PATH="$APP_FILE"
-echo "scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH $USER_NAME@$INSTANCE_IP:$REMOTE_FILE_PATH"
-scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH $USER_NAME@$INSTANCE_IP:$REMOTE_FILE_PATH
+  echo "Change script dir permission"
+  chmod_cmd="sudo chmod -R 777 /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH"
+  ssh_to_crawler $chmod_cmd
 
-#FIXME: extract to a method
-#UNTAR APP FILE
-echo "EXTRACTING SEBAL-Scheduler..."
-REMOTE_COMMAND="tar -vzxf $REMOTE_FILE_PATH";
-echo "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND"
-ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p $INSTANCE_PORT -i $PRIVATE_KEY_FILE  $USER_NAME@$INSTANCE_IP $REMOTE_COMMAND
+  echo "Mounting volume"
+  mount_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/mount_partition.sh $STORAGE_COMMAND"
+  ssh_to_crawler $cmd_cmd
+  sed -i "/CRAWLER_STORAGE_FORMATED=/ s/=.*/=YES/" $CRAWLER_EXECUTION_INFO
 
-#FIXME: extract to a method
-#PREPARING CERT FILE SCP COMMAND
-echo "UPLOAD CERTIFICATES..."
-LOCAL_FILE_PATH="/$VOMS_CERT_FOLDER/$VOMS_CERT_FILE";
-FILE_PATH="/$REMOTE_VOMS_CERT_FOLDER/$VOMS_CERT_FILE";
-#Coping certificate file to Crawler VM
-echo "scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH $USER_NAME@$INSTANCE_IP:$REMOTE_FILE_PATH"
-scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P $INSTANCE_PORT -i $PRIVATE_KEY_FILE $LOCAL_FILE_PATH $USER_NAME@$INSTANCE_IP:$REMOTE_FILE_PATH
+  #do we need it here?
+  echo "Installing git"
+  install_git_cmd="sudo sh /$REMOTE_FILE_PATH/$LOCAL_FILE_PATH/install_git.sh"
+  ssh_to_crawler $install_git_cmd
 
-#FIXME: syntax error
-#FIXME: extract to a method
-# see what have to change to use this
-IFS=',' read -r -a extraPortsArray <<< $EXTRA_PORT
-arrayLength=${#extraPortsArray[@]};
-for (( i=0; i<${arrayLength}; i++ ));
-do
- actualPort=${extraPortsArray[$i]};
- if [[ $actualPort == *"nfs"* ]]; then
-  CRAWLER_NFS_PORT=$(echo $actualPort | cut -d":" -f3 | tr -d })
- fi
-done
+  # see if the name of the project will change
+  echo "Upload crawler package"
+  scp_to_crawler $APP_FILE_LOCAL_DIR/$APP_FILE $APP_FILE
 
-#Putting informations on Crawler execution info.
-sed -i "/CRAWLER_INSTANCE_ID=/ s/=.*/=$INSTANCE_ID/" $CRAWLER_EXECUTION_INFO
-sed -i "/CRAWLER_USER_NAME=/ s/=.*/=$USER_NAME/" $CRAWLER_EXECUTION_INFO
-sed -i "/CRAWLER_INSTANCE_IP=/ s/=.*/=$INSTANCE_IP/" $CRAWLER_EXECUTION_INFO
-sed -i "/CRAWLER_INSTANCE_PORT=/ s/=.*/=$INSTANCE_PORT/" $CRAWLER_EXECUTION_INFO
-sed -i "/CRAWLER_EXTRA_PORT=/ s/=.*/=$EXTRA_PORT/" $CRAWLER_EXECUTION_INFO
-sed -i "/CRAWLER_NFS_PORT=/ s/=.*/=$CRAWLER_NFS_PORT/" $CRAWLER_EXECUTION_INFO
+  echo "Extracting SEBAL-engine"
+  extract_cmd="tar -vzxf $REMOTE_FILE_PATH"
+  ssh_to_crawler $extract_cmd
+
+  echo "Upload certificates"
+  LOCAL_FILE_PATH="/$VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
+  FILE_PATH="/$REMOTE_VOMS_CERT_FOLDER/$VOMS_CERT_FILE"
+  scp_to_crawler $LOCAL_FILE_PATH $FILE_PATH
+
+  #FIXME dst dir of private key?
+  echo "Upload private key"
+  #scp_to_crawler $PRIVATE_KEY $REMOTE_FILE_PATH
+
+  CRAWLER_NFS_PORT=`parse_nfs_port`
+
+  #Putting informations on Crawler execution info.
+  sed -i "/CRAWLER_INSTANCE_ID=/ s/=.*/=$INSTANCE_ID/" $CRAWLER_EXECUTION_INFO
+  sed -i "/CRAWLER_USER_NAME=/ s/=.*/=$USER_NAME/" $CRAWLER_EXECUTION_INFO
+  sed -i "/CRAWLER_INSTANCE_IP=/ s/=.*/=$INSTANCE_IP/" $CRAWLER_EXECUTION_INFO
+  sed -i "/CRAWLER_INSTANCE_PORT=/ s/=.*/=$INSTANCE_PORT/" $CRAWLER_EXECUTION_INFO
+  sed -i "/CRAWLER_EXTRA_PORT=/ s/=.*/=$EXTRA_PORT/" $CRAWLER_EXECUTION_INFO
+  sed -i "/CRAWLER_NFS_PORT=/ s/=.*/=$CRAWLER_NFS_PORT/" $CRAWLER_EXECUTION_INFO
+}
+
+#do deploy
+main
